const pokemons = [
  {
    id: 1,
    name: "Bulbasaur",
    img: "https://projectpokemon.org/images/normal-sprite/bulbasaur.gif",
    types: ["Grass", "Poison"],
    attack: 49,
    defense: 49,
    hp: 45,
    moves: [
      { move: "Placaje", move_dmg: 40 },
      { move: "Látigo Cepa", move_dmg: 20 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Absorber", move_dmg: 20 },
    ],
  },
  {
    id: 2,
    name: "Ivysaur",
    img: "https://projectpokemon.org/images/normal-sprite/ivysaur.gif",
    types: ["Grass", "Poison"],
    attack: 62,
    defense: 63,
    hp: 60,
    moves: [
      { move: "Placaje", move_dmg: 40 },
      { move: "Látigo Cepa", move_dmg: 20 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Drenadoras", move_dmg: 10 },
    ],
  },
  {
    id: 3,
    name: "Venusaur",
    img: "https://projectpokemon.org/images/normal-sprite/venusaur.gif",
    types: ["Grass", "Poison"],
    attack: 82,
    defense: 83,
    hp: 80,
    moves: [
      { move: "Placaje", move_dmg: 40 },
      { move: "Látigo Cepa", move_dmg: 20 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Drenadoras", move_dmg: 10 },
    ],
  },
  {
    id: 4,
    name: "Charmander",
    img: "https://projectpokemon.org/images/normal-sprite/charmander.gif",
    types: ["Fire"],
    attack: 52,
    defense: 43,
    hp: 39,
    moves: [
      { move: "Arañazo", move_dmg: 40 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Embestir", move_dmg: 40 },
      { move: "Llamarada", move_dmg: 95 },
    ],
  },
  {
    id: 5,
    name: "Charmeleon",
    img: "https://projectpokemon.org/images/normal-sprite/charmeleon.gif",
    types: ["Fire"],
    attack: 64,
    defense: 58,
    hp: 58,
    moves: [
      { move: "Arañazo", move_dmg: 40 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Embestir", move_dmg: 40 },
      { move: "Llamarada", move_dmg: 95 },
    ],
  },
  {
    id: 6,
    name: "Charizard",
    img: "https://projectpokemon.org/images/normal-sprite/charizard.gif",
    types: ["Fire", "Flying"],
    attack: 84,
    defense: 78,
    hp: 78,
    moves: [
      { move: "Arañazo", move_dmg: 40 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Embestir", move_dmg: 40 },
      { move: "Llamarada", move_dmg: 95 },
    ],
  },
  {
    id: 7,
    name: "Squirtle",
    img: "https://projectpokemon.org/images/normal-sprite/squirtle.gif",
    types: ["Water"],
    attack: 48,
    defense: 65,
    hp: 44,
    moves: [
      { move: "Placaje", move_dmg: 40 },
      { move: "Burbuja", move_dmg: 20 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Pistola Agua", move_dmg: 40 },
    ],
  },
  {
    id: 8,
    name: "Wartortle",
    img: "https://projectpokemon.org/images/normal-sprite/wartortle.gif",
    types: ["Water"],
    attack: 63,
    defense: 80,
    hp: 59,
    moves: [
      { move: "Placaje", move_dmg: 40 },
      { move: "Burbuja", move_dmg: 20 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Pistola Agua", move_dmg: 40 },
    ],
  },
  {
    id: 9,
    name: "Blastoise",
    img: "https://projectpokemon.org/images/normal-sprite/blastoise.gif",
    types: ["Water"],
    attack: 83,
    defense: 100,
    hp: 79,
    moves: [
      { move: "Placaje", move_dmg: 40 },
      { move: "Burbuja", move_dmg: 20 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Pistola Agua", move_dmg: 40 },
    ],
  },
  {
    id: 10,
    name: "Caterpie",
    img: "https://projectpokemon.org/images/normal-sprite/caterpie.gif",
    types: ["Bug"],
    attack: 30,
    defense: 35,
    hp: 45,
    moves: [
      {
        move: "Placaje",
        dmg: 20,
      },
      {
        move: "Hilo Sedoso",
        dmg: 0,
      },
    ],
  },
  {
    id: 11,
    name: "Metapod",
    img: "https://projectpokemon.org/images/normal-sprite/metapod.gif",
    types: ["Bug"],
    attack: 20,
    defense: 55,
    hp: 50,
    moves: [
      {
        move: "Placaje",
        dmg: 20,
      },
      {
        move: "Hilo Sedoso",
        dmg: 0,
      },
    ],
  },
  {
    id: 12,
    name: "Butterfree",
    img: "https://projectpokemon.org/images/normal-sprite/butterfree.gif",
    types: ["Bug", "Flying"],
    attack: 45,
    defense: 50,
    hp: 60,
    moves: [
      { move: "Tornado", move_dmg: 40 },
      { move: "Psíquico", move_dmg: 90 },
      { move: "Paralizador", move_dmg: 0 },
      { move: "Viento Plata", move_dmg: 60 },
    ],
  },
  {
    id: 13,
    name: "Weedle",
    img: "https://projectpokemon.org/images/normal-sprite/weedle.gif",
    types: ["Bug", "Poison"],
    attack: 35,
    defense: 30,
    hp: 40,
    moves: [
      { move: "Picotazo Veneno", move_dmg: 15 },
      { move: "Desenrollar", move_dmg: 20 },
      { move: "Picotazo", move_dmg: 20 },
    ],
  },
  {
    id: 14,
    name: "Kakuna",
    img: "https://projectpokemon.org/images/normal-sprite/kakuna.gif",
    types: ["Bug", "Poison"],
    attack: 25,
    defense: 50,
    hp: 45,
    moves: [{ move: "Fortaleza", move_dmg: 0 }],
  },
  {
    id: 15,
    name: "Beedrill",
    img: "https://projectpokemon.org/images/normal-sprite/beedrill.gif",
    types: ["Bug", "Poison"],
    attack: 90,
    defense: 40,
    hp: 65,
    moves: [
      { move: "Picotazo Veneno", move_dmg: 15 },
      { move: "Tijera X", move_dmg: 80 },
      { move: "Doble Filo", move_dmg: 90 },
      { move: "Pico Taladro", move_dmg: 70 },
    ],
  },
  {
    id: 16,
    name: "Pidgey",
    img: "https://projectpokemon.org/images/normal-sprite/pidgey.gif",
    types: ["Normal", "Flying"],
    attack: 45,
    defense: 40,
    hp: 40,
    moves: [
      { move: "Placaje", move_dmg: 40 },
      { move: "Giro Aéreo", move_dmg: 60 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Ataque Rápido", move_dmg: 40 },
    ],
  },
  {
    id: 17,
    name: "Pidgeotto",
    img: "https://projectpokemon.org/images/normal-sprite/pidgeotto.gif",
    types: ["Normal", "Flying"],
    attack: 60,
    defense: 55,
    hp: 63,
    moves: [
      { move: "Placaje", move_dmg: 40 },
      { move: "Giro Aéreo", move_dmg: 60 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Ataque Rápido", move_dmg: 40 },
    ],
  },
  {
    id: 18,
    name: "Pidgeot",
    img: "https://projectpokemon.org/images/normal-sprite/pidgeot.gif",
    types: ["Normal", "Flying"],
    attack: 80,
    defense: 75,
    hp: 83,
    moves: [
      { move: "Placaje", move_dmg: 40 },
      { move: "Giro Aéreo", move_dmg: 60 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Ataque Rápido", move_dmg: 40 },
    ],
  },
  {
    id: 19,
    name: "Rattata",
    img: "https://projectpokemon.org/images/normal-sprite/rattata.gif",
    types: ["Normal"],
    attack: 56,
    defense: 35,
    hp: 30,
    moves: [
      { move: "Tacleada", move_dmg: 40 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Bofetón", move_dmg: 15 },
    ],
  },
  {
    id: 20,
    name: "Raticate",
    img: "https://projectpokemon.org/images/normal-sprite/raticate.gif",
    types: ["Normal"],
    attack: 81,
    defense: 60,
    hp: 55,
    moves: [
      { move: "Tacleada", move_dmg: 40 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Bofetón", move_dmg: 15 },
    ],
  },
  {
    id: 21,
    name: "Spearow",
    img: "https://projectpokemon.org/images/normal-sprite/spearow.gif",
    types: ["Normal", "Flying"],
    attack: 60,
    defense: 30,
    hp: 40,
    moves: [
      { move: "Ataque Rápido", move_dmg: 40 },
      { move: "Pico Taladro", move_dmg: 70 },
      { move: "Ataque Ala", move_dmg: 60 },
      { move: "Ala de Acero", move_dmg: 50 },
    ],
  },
  {
    id: 22,
    name: "Fearow",
    img: "https://projectpokemon.org/images/normal-sprite/fearow.gif",
    types: ["Normal", "Flying"],
    attack: 90,
    defense: 65,
    hp: 65,
    moves: [
      { move: "Pico Taladro", move_dmg: 70 },
      { move: "Ataque Ala", move_dmg: 60 },
      { move: "Hiperrayo", move_dmg: 90 },
      { move: "Tajo Aéreo", move_dmg: 60 },
    ],
  },
  {
    id: 23,
    name: "Ekans",
    img: "https://projectpokemon.org/images/normal-sprite/ekans.gif",
    types: ["Poison"],
    attack: 60,
    defense: 44,
    hp: 35,
    moves: [
      { move: "Constricción", move_dmg: 20 },
      { move: "Picotazo Veneno", move_dmg: 15 },
      { move: "Ácido", move_dmg: 40 },
      { move: "Cola Veneno", move_dmg: 60 },
    ],
  },
  {
    id: 24,
    name: "Arbok",
    img: "https://projectpokemon.org/images/normal-sprite/arbok.gif",
    types: ["Poison"],
    attack: 85,
    defense: 69,
    hp: 60,
    moves: [
      { move: "Mordisco", move_dmg: 60 },
      { move: "Cola Veneno", move_dmg: 60 },
      { move: "Ácido", move_dmg: 40 },
      { move: "Bofetón Lodo", move_dmg: 20 },
    ],
  },
  {
    id: 25,
    name: "Pikachu",
    img: "https://projectpokemon.org/images/normal-sprite/pikachu.gif",
    types: ["Electric"],
    attack: 55,
    defense: 40,
    hp: 35,
    moves: [
      { move: "Impactrueno", move_dmg: 40 },
      { move: "Rayo", move_dmg: 60 },
      { move: "Cola Férrea", move_dmg: 50 },
      { move: "Onda Trueno", move_dmg: 0 },
    ],
  },
  {
    id: 26,
    name: "Raichu",
    img: "https://projectpokemon.org/images/normal-sprite/raichu.gif",
    types: ["Electric"],
    attack: 90,
    defense: 55,
    hp: 60,
    moves: [
      { move: "Impactrueno", move_dmg: 40 },
      { move: "Rayo", move_dmg: 60 },
      { move: "Cola Férrea", move_dmg: 50 },
      { move: "Onda Trueno", move_dmg: 0 },
    ],
  },
  {
    id: 27,
    name: "Sandshrew",
    img: "https://projectpokemon.org/images/normal-sprite/sandshrew.gif",
    types: ["Ground"],
    attack: 75,
    defense: 85,
    hp: 50,
    moves: [
      { move: "Arañazo", move_dmg: 40 },
      { move: "Bofetón Lodo", move_dmg: 20 },
      { move: "Excavar", move_dmg: 80 },
      { move: "Garra Metal", move_dmg: 50 },
    ],
  },
  {
    id: 28,
    name: "Sandslash",
    img: "https://projectpokemon.org/images/normal-sprite/sandslash.gif",
    types: ["Ground"],
    attack: 100,
    defense: 110,
    hp: 75,
    moves: [
      { move: "Garra Metal", move_dmg: 50 },
      { move: "Terremoto", move_dmg: 80 },
      { move: "Golpe Furia", move_dmg: 45 },
      { move: "Cuchillada", move_dmg: 60 },
    ],
  },
  {
    id: 29,
    name: "Nidoran♀",
    img: "https://projectpokemon.org/images/normal-sprite/nidoran_f.gif",
    types: ["Poison"],
    attack: 47,
    defense: 52,
    hp: 55,
    moves: [
      { move: "Gruñido", move_dmg: 0 },
      { move: "Picotazo Veneno", move_dmg: 15 },
      { move: "Doble Patada", move_dmg: 30 },
      { move: "Bofetón Lodo", move_dmg: 20 },
    ],
  },
  {
    id: 30,
    name: "Nidorina",
    img: "https://projectpokemon.org/images/normal-sprite/nidorina.gif",
    types: ["Poison"],
    attack: 62,
    defense: 67,
    hp: 70,
    moves: [
      { move: "Doble Patada", move_dmg: 30 },
      { move: "Mordisco", move_dmg: 60 },
      { move: "Ácido", move_dmg: 40 },
      { move: "Ataque Furia", move_dmg: 45 },
    ],
  },
  {
    id: 31,
    name: "Nidoqueen",
    img: "https://projectpokemon.org/images/normal-sprite/nidoqueen.gif",
    types: ["Poison", "Ground"],
    attack: 92,
    defense: 87,
    hp: 90,
    moves: [
      { move: "Terremoto", move_dmg: 80 },
      { move: "Golpe Cuerpo", move_dmg: 60 },
      { move: "Doble Patada", move_dmg: 30 },
      { move: "Roca Afilada", move_dmg: 50 },
    ],
  },
  {
    id: 32,
    name: "Nidoran♂",
    img: "https://projectpokemon.org/images/normal-sprite/nidoran_m.gif",
    types: ["Poison"],
    attack: 57,
    defense: 40,
    hp: 46,
    moves: [
      { move: "Gruñido", move_dmg: 0 },
      { move: "Picotazo Veneno", move_dmg: 15 },
      { move: "Ataque Furia", move_dmg: 45 },
      { move: "Doble Patada", move_dmg: 30 },
    ],
  },
  {
    id: 33,
    name: "Nidorino",
    img: "https://projectpokemon.org/images/normal-sprite/nidorino.gif",
    types: ["Poison"],
    attack: 72,
    defense: 57,
    hp: 61,
    moves: [
      { move: "Mordisco", move_dmg: 60 },
      { move: "Picotazo Veneno", move_dmg: 15 },
      { move: "Ataque Furia", move_dmg: 45 },
      { move: "Doble Patada", move_dmg: 30 },
    ],
  },
  {
    id: 34,
    name: "Nidoking",
    img: "https://projectpokemon.org/images/normal-sprite/nidoking.gif",
    types: ["Poison", "Ground"],
    attack: 102,
    defense: 77,
    hp: 81,
    moves: [
      { move: "Terratemblor", move_dmg: 80 },
      { move: "Golpe Karate", move_dmg: 50 },
      { move: "Colmillo Veneno", move_dmg: 65 },
      { move: "Megacuerno", move_dmg: 70 },
    ],
  },
  {
    id: 35,
    name: "Clefairy",
    img: "https://projectpokemon.org/images/normal-sprite/clefairy.gif",
    types: ["Fairy"],
    attack: 45,
    defense: 48,
    hp: 70,
    moves: [
      { move: "Encanto", move_dmg: 0 },
      { move: "Rayo", move_dmg: 60 },
      { move: "Doble Bofetón", move_dmg: 35 },
      { move: "Rayo Lunar", move_dmg: 95 },
    ],
  },
  {
    id: 36,
    name: "Clefable",
    img: "https://projectpokemon.org/images/normal-sprite/clefable.gif",
    types: ["Fairy"],
    attack: 70,
    defense: 73,
    hp: 95,
    moves: [
      { move: "Doble Bofetón", move_dmg: 35 },
      { move: "Eco Metálico", move_dmg: 0 },
      { move: "Doble Rayo", move_dmg: 70 },
      { move: "Meteorobola", move_dmg: 60 },
    ],
  },
  {
    id: 37,
    name: "Vulpix",
    img: "https://projectpokemon.org/images/normal-sprite/vulpix.gif",
    types: ["Fire"],
    attack: 41,
    defense: 40,
    hp: 38,
    moves: [
      { move: "Ascuas", move_dmg: 40 },
      { move: "Llamarada", move_dmg: 90 },
      { move: "Ataque Rápido", move_dmg: 40 },
      { move: "Hipnosis", move_dmg: 0 },
    ],
  },
  {
    id: 38,
    name: "Ninetales",
    img: "https://projectpokemon.org/images/normal-sprite/ninetales.gif",
    types: ["Fire"],
    attack: 76,
    defense: 75,
    hp: 73,
    moves: [
      { move: "Llamarada", move_dmg: 90 },
      { move: "Luz Mística", move_dmg: 60 },
      { move: "Hipnosis", move_dmg: 0 },
      { move: "Colmillo Ígneo", move_dmg: 65 },
    ],
  },
  {
    id: 39,
    name: "Jigglypuff",
    img: "https://projectpokemon.org/images/normal-sprite/jigglypuff.gif",
    types: ["Normal", "Fairy"],
    attack: 45,
    defense: 20,
    hp: 115,
    moves: [
      { move: "Canto", move_dmg: 0 },
      { move: "Bofetón Lodo", move_dmg: 30 },
      { move: "Rizo Defensa", move_dmg: 0 },
      { move: "Desenrollar", move_dmg: 25 },
    ],
  },
  {
    id: 40,
    name: "Wigglytuff",
    img: "https://projectpokemon.org/images/normal-sprite/wigglytuff.gif",
    types: ["Normal", "Fairy"],
    attack: 70,
    defense: 45,
    hp: 140,
    moves: [
      { move: "Doble Bofetón", move_dmg: 35 },
      { move: "Canto", move_dmg: 0 },
      { move: "Rayo", move_dmg: 60 },
      { move: "Rayo Solar", move_dmg: 80 },
    ],
  },
  {
    id: 41,
    name: "Zubat",
    img: "https://projectpokemon.org/images/normal-sprite/zubat.gif",
    types: ["Poison", "Flying"],
    attack: 45,
    defense: 35,
    hp: 40,
    moves: [
      { move: "Látigo Cepa", move_dmg: 20 },
      { move: "Supersónico", move_dmg: 0 },
      { move: "Ataque Rápido", move_dmg: 40 },
    ],
  },
  {
    id: 42,
    name: "Golbat",
    img: "https://projectpokemon.org/images/normal-sprite/golbat.gif",
    types: ["Poison", "Flying"],
    attack: 80,
    defense: 70,
    hp: 75,
    moves: [
      { move: "Látigo Cepa", move_dmg: 20 },
      { move: "Supersónico", move_dmg: 0 },
      { move: "Ataque Rápido", move_dmg: 40 },
    ],
  },
  {
    id: 43,
    name: "Oddish",
    img: "https://projectpokemon.org/images/normal-sprite/oddish.gif",
    types: ["Grass", "Poison"],
    attack: 50,
    defense: 55,
    hp: 45,
    moves: [
      { move: "Absorber", move_dmg: 20 },
      { move: "Paralizador", move_dmg: 0 },
      { move: "Bomba Germen", move_dmg: 55 },
      { move: "Polvo Veneno", move_dmg: 0 },
    ],
  },
  {
    id: 44,
    name: "Gloom",
    img: "https://projectpokemon.org/images/normal-sprite/gloom.gif",
    types: ["Grass", "Poison"],
    attack: 65,
    defense: 70,
    hp: 60,
    moves: [
      { move: "Absorber", move_dmg: 20 },
      { move: "Bomba Germen", move_dmg: 55 },
      { move: "Polvo Veneno", move_dmg: 0 },
      { move: "Derribo", move_dmg: 40 },
    ],
  },
  {
    id: 45,
    name: "Vileplume",
    img: "https://projectpokemon.org/images/normal-sprite/vileplume.gif",
    types: ["Grass", "Poison"],
    attack: 80,
    defense: 85,
    hp: 75,
    moves: [
      { move: "Polvo Veneno", move_dmg: 0 },
      { move: "Absorber", move_dmg: 20 },
      { move: "Rayo Solar", move_dmg: 80 },
      { move: "Bomba Lodo", move_dmg: 65 },
    ],
  },
  {
    id: 46,
    name: "Paras",
    img: "https://projectpokemon.org/images/normal-sprite/paras.gif",
    types: ["Bug", "Grass"],
    attack: 70,
    defense: 55,
    hp: 35,
    moves: [
      { move: "Picotazo", move_dmg: 35 },
      { move: "Látigo Cepa", move_dmg: 20 },
      { move: "Polvo Stun", move_dmg: 0 },
      { move: "Giro Rápido", move_dmg: 20 },
    ],
  },
  {
    id: 47,
    name: "Parasect",
    img: "https://projectpokemon.org/images/normal-sprite/parasect.gif",
    types: ["Bug", "Grass"],
    attack: 95,
    defense: 80,
    hp: 60,
    moves: [
      { move: "Picotazo", move_dmg: 35 },
      { move: "Látigo Cepa", move_dmg: 20 },
      { move: "Polvo Stun", move_dmg: 0 },
      { move: "Bomba Germen", move_dmg: 55 },
    ],
  },
  {
    id: 48,
    name: "Venonat",
    img: "https://projectpokemon.org/images/normal-sprite/venonat.gif",
    types: ["Bug", "Poison"],
    attack: 55,
    defense: 50,
    hp: 60,
    moves: [
      { move: "Confusión", move_dmg: 50 },
      { move: "Polvo Veneno", move_dmg: 0 },
      { move: "Látigo Cepa", move_dmg: 20 },
      { move: "Manto de Polvo", move_dmg: 0 },
    ],
  },
  {
    id: 49,
    name: "Venomoth",
    img: "https://projectpokemon.org/images/normal-sprite/venomoth.gif",
    types: ["Bug", "Poison"],
    attack: 65,
    defense: 60,
    hp: 70,
    moves: [
      { move: "Confusión", move_dmg: 50 },
      { move: "Bomba Germen", move_dmg: 55 },
      { move: "Polvo Veneno", move_dmg: 0 },
      { move: "Bola Sombra", move_dmg: 30 },
    ],
  },
  {
    id: 50,
    name: "Diglett",
    img: "https://projectpokemon.org/images/normal-sprite/diglett.gif",
    types: ["Ground"],
    attack: 55,
    defense: 25,
    hp: 10,
    moves: [
      { move: "Ataque Rápido", move_dmg: 40 },
      { move: "Excavar", move_dmg: 60 },
      { move: "Golpe Cabeza", move_dmg: 50 },
      { move: "Bomba Fango", move_dmg: 65 },
    ],
  },
  {
    id: 51,
    name: "Dugtrio",
    img: "https://projectpokemon.org/images/normal-sprite/dugtrio.gif",
    types: ["Ground"],
    attack: 100,
    defense: 50,
    hp: 35,
    moves: [
      { move: "Ataque Rápido", move_dmg: 40 },
      { move: "Excavar", move_dmg: 60 },
      { move: "Golpe Cabeza", move_dmg: 50 },
      { move: "Bomba Fango", move_dmg: 65 },
    ],
  },
  {
    id: 52,
    name: "Meowth",
    img: "https://projectpokemon.org/images/normal-sprite/meowth.gif",
    types: ["Normal"],
    attack: 45,
    defense: 35,
    hp: 40,
    moves: [
      { move: "Arañazo", move_dmg: 40 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Bofetón", move_dmg: 15 },
    ],
  },
  {
    id: 53,
    name: "Persian",
    img: "https://projectpokemon.org/images/normal-sprite/persian.gif",
    types: ["Normal"],
    attack: 70,
    defense: 60,
    hp: 65,
    moves: [
      { move: "Arañazo", move_dmg: 40 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Bofetón", move_dmg: 15 },
    ],
  },
  {
    id: 54,
    name: "Psyduck",
    img: "https://projectpokemon.org/images/normal-sprite/psyduck.gif",
    types: ["Water"],
    attack: 52,
    defense: 48,
    hp: 50,
    moves: [
      { move: "Confusión", move_dmg: 50 },
      { move: "Poder Psíquico", move_dmg: 90 },
      { move: "Burbujas", move_dmg: 20 },
      { move: "Hidropulsor", move_dmg: 40 },
    ],
  },
  {
    id: 55,
    name: "Golduck",
    img: "https://projectpokemon.org/images/normal-sprite/golduck.gif",
    types: ["Water"],
    attack: 82,
    defense: 78,
    hp: 80,
    moves: [
      { move: "Confusión", move_dmg: 50 },
      { move: "Poder Psíquico", move_dmg: 90 },
      { move: "Hidrobomba", move_dmg: 110 },
      { move: "Puño Hielo", move_dmg: 40 },
    ],
  },
  {
    id: 56,
    name: "Mankey",
    img: "https://projectpokemon.org/images/normal-sprite/mankey.gif",
    types: ["Fighting"],
    attack: 80,
    defense: 35,
    hp: 40,
    moves: [
      { move: "Puño Karate", move_dmg: 40 },
      { move: "Puño Fuego", move_dmg: 40 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Ataque Rápido", move_dmg: 40 },
    ],
  },
  {
    id: 57,
    name: "Primeape",
    img: "https://projectpokemon.org/images/normal-sprite/primeape.gif",
    types: ["Fighting"],
    attack: 105,
    defense: 60,
    hp: 65,
    moves: [
      { move: "Puño Karate", move_dmg: 40 },
      { move: "Puño Fuego", move_dmg: 40 },
      { move: "Puño Hielo", move_dmg: 40 },
      { move: "Rencor", move_dmg: 0 },
    ],
  },
  {
    id: 58,
    name: "Growlithe",
    img: "https://projectpokemon.org/images/normal-sprite/growlithe.gif",
    types: ["Fire"],
    attack: 70,
    defense: 45,
    hp: 55,
    moves: [
      { move: "Lanzallamas", move_dmg: 60 },
      { move: "Mordisco", move_dmg: 40 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Armadura", move_dmg: 0 },
    ],
  },
  {
    id: 59,
    name: "Arcanine",
    img: "https://projectpokemon.org/images/normal-sprite/arcanine.gif",
    types: ["Fire"],
    attack: 110,
    defense: 80,
    hp: 90,
    moves: [
      { move: "Ascuas", move_dmg: 40 },
      { move: "Llamarada", move_dmg: 90 },
      { move: "Mordisco", move_dmg: 60 },
      { move: "Velocidad Extrema", move_dmg: 80 },
    ],
  },
  {
    id: 60,
    name: "Poliwag",
    img: "https://projectpokemon.org/images/normal-sprite/poliwag.gif",
    types: ["Water"],
    attack: 50,
    defense: 40,
    hp: 40,
    moves: [
      { move: "Placaje", move_dmg: 40 },
      { move: "Burbuja", move_dmg: 20 },
      { move: "Gruñido", move_dmg: 0 },
    ],
  },
  {
    id: 61,
    name: "Poliwhirl",
    img: "https://projectpokemon.org/images/normal-sprite/poliwhirl.gif",
    types: ["Water"],
    attack: 65,
    defense: 65,
    hp: 65,
    moves: [
      { move: "Placaje", move_dmg: 40 },
      { move: "Burbuja", move_dmg: 20 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Puño Agua", move_dmg: 50 },
    ],
  },
  {
    id: 62,
    name: "Poliwrath",
    img: "https://projectpokemon.org/images/normal-sprite/poliwrath.gif",
    types: ["Water", "Fighting"],
    attack: 85,
    defense: 95,
    hp: 90,
    moves: [
      { move: "Placaje", move_dmg: 40 },
      { move: "Burbuja", move_dmg: 20 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Puño Agua", move_dmg: 50 },
    ],
  },
  {
    id: 63,
    name: "Abra",
    img: "https://projectpokemon.org/images/normal-sprite/abra.gif",
    types: ["Psychic"],
    attack: 20,
    defense: 15,
    hp: 25,
    moves: [
      { move: "Confusión", move_dmg: 50 },
      { move: "Psíquico", move_dmg: 90 },
      { move: "Rayo", move_dmg: 60 },
      { move: "Doble Equipo", move_dmg: 0 },
    ],
  },
  {
    id: 64,
    name: "Kadabra",
    img: "https://projectpokemon.org/images/normal-sprite/kadabra.gif",
    types: ["Psychic"],
    attack: 35,
    defense: 30,
    hp: 40,
    moves: [
      { move: "Confusión", move_dmg: 50 },
      { move: "Psíquico", move_dmg: 90 },
      { move: "Rayo", move_dmg: 60 },
      { move: "Doble Equipo", move_dmg: 0 },
    ],
  },
  {
    id: 65,
    name: "Alakazam",
    img: "https://projectpokemon.org/images/normal-sprite/alakazam.gif",
    types: ["Psychic"],
    attack: 50,
    defense: 45,
    hp: 55,
    moves: [
      { move: "Confusión", move_dmg: 50 },
      { move: "Psíquico", move_dmg: 90 },
      { move: "Rayo", move_dmg: 60 },
      { move: "Doble Equipo", move_dmg: 0 },
    ],
  },
  {
    id: 66,
    name: "Machop",
    img: "https://projectpokemon.org/images/normal-sprite/machop.gif",
    types: ["Fighting"],
    attack: 80,
    defense: 50,
    hp: 70,
    moves: [
      { move: "Golpe Bajo", move_dmg: 30 },
      { move: "Golpe Cuerpo", move_dmg: 50 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Puño Karate", move_dmg: 50 },
    ],
  },
  {
    id: 67,
    name: "Machoke",
    img: "https://projectpokemon.org/images/normal-sprite/machoke.gif",
    types: ["Fighting"],
    attack: 100,
    defense: 70,
    hp: 80,
    moves: [
      { move: "Golpe Bajo", move_dmg: 30 },
      { move: "Golpe Cuerpo", move_dmg: 50 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Puño Karate", move_dmg: 50 },
    ],
  },
  {
    id: 68,
    name: "Machamp",
    img: "https://projectpokemon.org/images/normal-sprite/machamp.gif",
    types: ["Fighting"],
    attack: 130,
    defense: 80,
    hp: 90,
    moves: [
      { move: "Golpe Bajo", move_dmg: 30 },
      { move: "Golpe Cuerpo", move_dmg: 50 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Puño Karate", move_dmg: 50 },
    ],
  },
  {
    id: 69,
    name: "Bellsprout",
    img: "https://projectpokemon.org/images/normal-sprite/bellsprout.gif",
    types: ["Grass", "Poison"],
    attack: 75,
    defense: 35,
    hp: 50,
    moves: [
      { move: "Látigo Cepa", move_dmg: 20 },
      { move: "Absorber", move_dmg: 20 },
      { move: "Gruñido", move_dmg: 0 },
    ],
  },
  {
    id: 70,
    name: "Weepinbell",
    img: "https://projectpokemon.org/images/normal-sprite/weepinbell.gif",
    types: ["Grass", "Poison"],
    attack: 90,
    defense: 50,
    hp: 65,
    moves: [
      { move: "Látigo Cepa", move_dmg: 20 },
      { move: "Absorber", move_dmg: 20 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Drenadoras", move_dmg: 10 },
    ],
  },
  {
    id: 71,
    name: "Victreebel",
    img: "https://projectpokemon.org/images/normal-sprite/victreebel.gif",
    types: ["Grass", "Poison"],
    attack: 105,
    defense: 65,
    hp: 80,
    moves: [
      { move: "Látigo Cepa", move_dmg: 20 },
      { move: "Absorber", move_dmg: 20 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Drenadoras", move_dmg: 10 },
    ],
  },
  {
    id: 72,
    name: "Tentacool",
    img: "https://projectpokemon.org/images/normal-sprite/tentacool.gif",
    types: ["Water", "Poison"],
    attack: 40,
    defense: 35,
    hp: 40,
    moves: [
      { move: "Chorro de Agua", move_dmg: 40 },
      { move: "Pico Veneno", move_dmg: 40 },
      { move: "Burbujas", move_dmg: 20 },
      { move: "Puño Sombra", move_dmg: 40 },
    ],
  },
  {
    id: 73,
    name: "Tentacruel",
    img: "https://projectpokemon.org/images/normal-sprite/tentacruel.gif",
    types: ["Water", "Poison"],
    attack: 50,
    defense: 40,
    hp: 50,
    moves: [
      { move: "Chorro de Agua", move_dmg: 40 },
      { move: "Hidrobomba", move_dmg: 110 },
      { move: "Puño Hielo", move_dmg: 40 },
      { move: "Pico Veneno", move_dmg: 40 },
    ],
  },
  {
    id: 74,
    name: "Geodude",
    img: "https://projectpokemon.org/images/normal-sprite/geodude.gif",
    types: ["Rock", "Ground"],
    attack: 55,
    defense: 45,
    hp: 55,
    moves: [
      { move: "Tacleada", move_dmg: 40 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Roca Afilada", move_dmg: 50 },
    ],
  },
  {
    id: 75,
    name: "Graveler",
    img: "https://projectpokemon.org/images/normal-sprite/graveler.gif",
    types: ["Rock", "Ground"],
    attack: 60,
    defense: 50,
    hp: 60,
    moves: [
      { move: "Tacleada", move_dmg: 40 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Roca Afilada", move_dmg: 50 },
    ],
  },
  {
    id: 76,
    name: "Golem",
    img: "https://projectpokemon.org/images/normal-sprite/golem.gif",
    types: ["Rock", "Ground"],
    attack: 65,
    defense: 55,
    hp: 65,
    moves: [
      { move: "Tacleada", move_dmg: 40 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Roca Afilada", move_dmg: 50 },
    ],
  },
  {
    id: 77,
    name: "Ponyta",
    img: "https://projectpokemon.org/images/normal-sprite/ponyta.gif",
    types: ["Fire"],
    attack: 60,
    defense: 45,
    hp: 50,
    moves: [
      { move: "Llamarada", move_dmg: 40 },
      { move: "Giro Fuego", move_dmg: 35 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Ascuas", move_dmg: 40 },
    ],
  },
  {
    id: 78,
    name: "Rapidash",
    img: "https://projectpokemon.org/images/normal-sprite/rapidash.gif",
    types: ["Fire"],
    attack: 65,
    defense: 55,
    hp: 65,
    moves: [
      { move: "Llamarada", move_dmg: 40 },
      { move: "Corte Fuego", move_dmg: 50 },
      { move: "Giro Fuego", move_dmg: 35 },
      { move: "Ardor", move_dmg: 45 },
    ],
  },
  {
    id: 79,
    name: "Slowpoke",
    img: "https://projectpokemon.org/images/normal-sprite/slowpoke.gif",
    types: ["Water", "Psychic"],
    attack: 55,
    defense: 45,
    hp: 50,
    moves: [
      { move: "Confusión", move_dmg: 50 },
      { move: "Poder Psíquico", move_dmg: 90 },
      { move: "Burbujas", move_dmg: 20 },
      { move: "Hidropulsor", move_dmg: 40 },
    ],
  },
  {
    id: 80,
    name: "Slowbro",
    img: "https://projectpokemon.org/images/normal-sprite/slowbro.gif",
    types: ["Water", "Psychic"],
    attack: 65,
    defense: 50,
    hp: 65,
    moves: [
      { move: "Confusión", move_dmg: 50 },
      { move: "Poder Psíquico", move_dmg: 90 },
      { move: "Hidrobomba", move_dmg: 110 },
      { move: "Puño Hielo", move_dmg: 40 },
    ],
  },
  {
    id: 81,
    name: "Magnemite",
    img: "https://projectpokemon.org/images/normal-sprite/magnemite.gif",
    types: ["Electric", "Steel"],
    attack: 45,
    defense: 40,
    hp: 35,
    moves: [
      { move: "Chispazo", move_dmg: 40 },
      { move: "Puño Trueno", move_dmg: 40 },
      { move: "Sorpresa", move_dmg: 0 },
      { move: "Puño Rayo", move_dmg: 40 },
    ],
  },
  {
    id: 82,
    name: "Magneton",
    img: "https://projectpokemon.org/images/normal-sprite/magneton.gif",
    types: ["Electric", "Steel"],
    attack: 50,
    defense: 50,
    hp: 45,
    moves: [
      { move: "Chispazo", move_dmg: 40 },
      { move: "Puño Trueno", move_dmg: 40 },
      { move: "Rayo", move_dmg: 50 },
      { move: "Puño Rayo", move_dmg: 40 },
    ],
  },
  {
    id: 83,
    name: "Farfetch’d",
    img: "https://projectpokemon.org/images/normal-sprite/farfetchd.gif",
    types: ["Normal", "Flying"],
    attack: 65,
    defense: 55,
    hp: 52,
    moves: [
      { move: "Hoja Afilada", move_dmg: 35 },
      { move: "Picotazo", move_dmg: 35 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Vuelo", move_dmg: 50 },
    ],
  },
  {
    id: 84,
    name: "Doduo",
    img: "https://projectpokemon.org/images/normal-sprite/doduo.gif",
    types: ["Normal", "Flying"],
    attack: 85,
    defense: 45,
    hp: 65,
    moves: [
      { move: "Ataque Rápido", move_dmg: 40 },
      { move: "Picotazo", move_dmg: 35 },
      { move: "Patada Baja", move_dmg: 35 },
      { move: "Golpe Bajo", move_dmg: 40 },
    ],
  },
  {
    id: 85,
    name: "Dodrio",
    img: "https://projectpokemon.org/images/normal-sprite/dodrio.gif",
    types: ["Normal", "Flying"],
    attack: 110,
    defense: 70,
    hp: 95,
    moves: [
      { move: "Ataque Rápido", move_dmg: 40 },
      { move: "Picotazo", move_dmg: 35 },
      { move: "Patada Baja", move_dmg: 35 },
      { move: "Golpe Bajo", move_dmg: 40 },
    ],
  },
  {
    id: 86,
    name: "Seel",
    img: "https://projectpokemon.org/images/normal-sprite/seel.gif",
    types: ["Water"],
    attack: 45,
    defense: 55,
    hp: 65,
    moves: [
      { move: "Chorro de Agua", move_dmg: 40 },
      { move: "Burbujas", move_dmg: 20 },
      { move: "Puño Hielo", move_dmg: 40 },
      { move: "Hidropulsor", move_dmg: 40 },
    ],
  },
  {
    id: 87,
    name: "Dewgong",
    img: "https://projectpokemon.org/images/normal-sprite/dewgong.gif",
    types: ["Water", "Ice"],
    attack: 70,
    defense: 80,
    hp: 90,
    moves: [
      { move: "Chorro de Agua", move_dmg: 40 },
      { move: "Hidrobomba", move_dmg: 110 },
      { move: "Puño Hielo", move_dmg: 40 },
      { move: "Aullido", move_dmg: 0 },
    ],
  },
  {
    id: 88,
    name: "Grimer",
    img: "https://projectpokemon.org/images/normal-sprite/grimer.gif",
    types: ["Poison"],
    attack: 80,
    defense: 50,
    hp: 70,
    moves: [
      { move: "Golpe Lodo", move_dmg: 40 },
      { move: "Polvo Veneno", move_dmg: 0 },
      { move: "Tóxico", move_dmg: 0 },
      { move: "Maldición", move_dmg: 0 },
    ],
  },
  {
    id: 89,
    name: "Muk",
    img: "https://projectpokemon.org/images/normal-sprite/muk.gif",
    types: ["Poison"],
    attack: 105,
    defense: 75,
    hp: 105,
    moves: [
      { move: "Golpe Lodo", move_dmg: 40 },
      { move: "Polvo Veneno", move_dmg: 0 },
      { move: "Tóxico", move_dmg: 0 },
      { move: "Bomba Lodo", move_dmg: 60 },
    ],
  },
  {
    id: 90,
    name: "Shellder",
    img: "https://projectpokemon.org/images/normal-sprite/shellder.gif",
    types: ["Water"],
    attack: 65,
    defense: 100,
    hp: 30,
    moves: [
      { move: "Burbujas", move_dmg: 20 },
      { move: "Puño Hielo", move_dmg: 40 },
      { move: "Triturar", move_dmg: 40 },
      { move: "Rugido", move_dmg: 0 },
    ],
  },
  {
    id: 91,
    name: "Cloyster",
    img: "https://projectpokemon.org/images/normal-sprite/cloyster.gif",
    types: ["Water", "Ice"],
    attack: 95,
    defense: 180,
    hp: 50,
    moves: [
      { move: "Burbujas", move_dmg: 20 },
      { move: "Hidrobomba", move_dmg: 110 },
      { move: "Puño Hielo", move_dmg: 40 },
      { move: "Triturar", move_dmg: 40 },
    ],
  },
  {
    id: 92,
    name: "Gastly",
    img: "https://projectpokemon.org/images/normal-sprite/gastly.gif",
    types: ["Ghost", "Poison"],
    attack: 35,
    defense: 30,
    hp: 30,
    moves: [
      { move: "Lanza Fuego", move_dmg: 40 },
      { move: "Bola Sombra", move_dmg: 30 },
      { move: "Hipnosis", move_dmg: 0 },
      { move: "Puño Fuego", move_dmg: 40 },
    ],
  },
  {
    id: 93,
    name: "Haunter",
    img: "https://projectpokemon.org/images/normal-sprite/haunter.gif",
    types: ["Ghost", "Poison"],
    attack: 50,
    defense: 45,
    hp: 45,
    moves: [
      { move: "Lengüetazo", move_dmg: 20 },
      { move: "Hipnosis", move_dmg: 0 },
      { move: "Bola Sombra", move_dmg: 80 },
      { move: "Puño Sombra", move_dmg: 50 },
    ],
  },
  {
    id: 94,
    name: "Gengar",
    img: "https://projectpokemon.org/images/normal-sprite/gengar.gif",
    types: ["Ghost", "Poison"],
    attack: 65,
    defense: 60,
    hp: 60,
    moves: [
      { move: "Lengüetazo", move_dmg: 20 },
      { move: "Hipnosis", move_dmg: 0 },
      { move: "Bola Sombra", move_dmg: 80 },
      { move: "Puño Sombra", move_dmg: 50 },
    ],
  },
  {
    id: 95,
    name: "Onix",
    img: "https://projectpokemon.org/images/normal-sprite/onix.gif",
    types: ["Rock", "Ground"],
    attack: 45,
    defense: 160,
    hp: 35,
    moves: [
      { move: "Tierra Viva", move_dmg: 35 },
      { move: "Roca Afilada", move_dmg: 50 },
      { move: "Golpe Cuerpo", move_dmg: 40 },
      { move: "Gruñido", move_dmg: 0 },
    ],
  },
  {
    id: 96,
    name: "Drowzee",
    img: "https://projectpokemon.org/images/normal-sprite/drowzee.gif",
    types: ["Psychic"],
    attack: 48,
    defense: 45,
    hp: 60,
    moves: [
      { move: "Confusión", move_dmg: 50 },
      { move: "Poder Psíquico", move_dmg: 90 },
      { move: "Puño Psíquico", move_dmg: 40 },
      { move: "Hipnosis", move_dmg: 0 },
    ],
  },
  {
    id: 97,
    name: "Hypno",
    img: "https://projectpokemon.org/images/normal-sprite/hypno.gif",
    types: ["Psychic"],
    attack: 73,
    defense: 70,
    hp: 85,
    moves: [
      { move: "Confusión", move_dmg: 50 },
      { move: "Poder Psíquico", move_dmg: 90 },
      { move: "Puño Psíquico", move_dmg: 40 },
      { move: "Pesadilla", move_dmg: 0 },
    ],
  },
  {
    id: 98,
    name: "Krabby",
    img: "https://projectpokemon.org/images/normal-sprite/krabby.gif",
    types: ["Water"],
    attack: 105,
    defense: 90,
    hp: 30,
    moves: [
      { move: "Pico Acero", move_dmg: 40 },
      { move: "Burbuja", move_dmg: 20 },
      { move: "Puño Agua", move_dmg: 40 },
      { move: "Picotazo", move_dmg: 35 },
    ],
  },
  {
    id: 99,
    name: "Kingler",
    img: "https://projectpokemon.org/images/normal-sprite/kingler.gif",
    types: ["Water"],
    attack: 130,
    defense: 115,
    hp: 55,
    moves: [
      { move: "Pico Acero", move_dmg: 40 },
      { move: "Puño Agua", move_dmg: 40 },
      { move: "Hidrobomba", move_dmg: 110 },
      { move: "Triturar", move_dmg: 40 },
    ],
  },
  {
    id: 100,
    name: "Voltorb",
    img: "https://projectpokemon.org/images/normal-sprite/voltorb.gif",
    types: ["Electric"],
    attack: 30,
    defense: 50,
    hp: 40,
    moves: [
      { move: "Chispazo", move_dmg: 40 },
      { move: "Explosión", move_dmg: 250 },
      { move: "Puño Trueno", move_dmg: 40 },
      { move: "Sorpresa", move_dmg: 0 },
    ],
  },
  {
    id: 101,
    name: "Electrode",
    img: "https://projectpokemon.org/images/normal-sprite/electrode.gif",
    types: ["Electric"],
    attack: 50,
    defense: 70,
    hp: 60,
    moves: [
      { move: "Chispazo", move_dmg: 40 },
      { move: "Puño Trueno", move_dmg: 40 },
      { move: "Rayo", move_dmg: 50 },
      { move: "Explosión", move_dmg: 250 },
    ],
  },
  {
    id: 102,
    name: "Exeggcute",
    img: "https://projectpokemon.org/images/normal-sprite/exeggcute.gif",
    types: ["Grass", "Psychic"],
    attack: 40,
    defense: 80,
    hp: 60,
    moves: [
      { move: "Confusión", move_dmg: 50 },
      { move: "Hipnosis", move_dmg: 0 },
      { move: "Hoja Afilada", move_dmg: 35 },
      { move: "Bomba Germen", move_dmg: 55 },
    ],
  },
  {
    id: 103,
    name: "Exeggutor",
    img: "https://projectpokemon.org/images/normal-sprite/exeggutor.gif",
    types: ["Grass", "Psychic"],
    attack: 95,
    defense: 85,
    hp: 95,
    moves: [
      { move: "Confusión", move_dmg: 50 },
      { move: "Poder Psíquico", move_dmg: 90 },
      { move: "Hoja Afilada", move_dmg: 35 },
      { move: "Bomba Germen", move_dmg: 55 },
    ],
  },
  {
    id: 104,
    name: "Cubone",
    img: "https://projectpokemon.org/images/normal-sprite/cubone.gif",
    types: ["Ground"],
    attack: 50,
    defense: 95,
    hp: 50,
    moves: [
      { move: "Golpe Cabeza", move_dmg: 40 },
      { move: "Bola Sombra", move_dmg: 30 },
      { move: "Puño Hielo", move_dmg: 40 },
      { move: "Látigo Cepa", move_dmg: 20 },
    ],
  },
  {
    id: 105,
    name: "Marowak",
    img: "https://projectpokemon.org/images/normal-sprite/marowak.gif",
    types: ["Ground"],
    attack: 80,
    defense: 110,
    hp: 60,
    moves: [
      { move: "Golpe Cabeza", move_dmg: 40 },
      { move: "Puño Hielo", move_dmg: 40 },
      { move: "Látigo Cepa", move_dmg: 20 },
      { move: "Hueso Palo", move_dmg: 50 },
    ],
  },
  {
    id: 106,
    name: "Hitmonlee",
    img: "https://projectpokemon.org/images/normal-sprite/hitmonlee.gif",
    types: ["Fighting"],
    attack: 120,
    defense: 53,
    hp: 50,
    moves: [
      { move: "Patada Baja", move_dmg: 35 },
      { move: "Patada Alta", move_dmg: 60 },
      { move: "Puño Karate", move_dmg: 40 },
      { move: "Patada Giro", move_dmg: 50 },
    ],
  },
  {
    id: 107,
    name: "Hitmonchan",
    img: "https://projectpokemon.org/images/normal-sprite/hitmonchan.gif",
    types: ["Fighting"],
    attack: 105,
    defense: 79,
    hp: 50,
    moves: [
      { move: "Puño Fuego", move_dmg: 40 },
      { move: "Puño Trueno", move_dmg: 40 },
      { move: "Puño Hielo", move_dmg: 40 },
      { move: "Puño Karate", move_dmg: 40 },
    ],
  },
  {
    id: 108,
    name: "Lickitung",
    img: "https://projectpokemon.org/images/normal-sprite/lickitung.gif",
    types: ["Normal"],
    attack: 55,
    defense: 75,
    hp: 90,
    moves: [
      { move: "Látigo Cepa", move_dmg: 20 },
      { move: "Lengüetazo", move_dmg: 15 },
      { move: "Gruñido", move_dmg: 0 },
      { move: "Golpe Cuerpo", move_dmg: 40 },
    ],
  },
  {
    id: 109,
    name: "Koffing",
    img: "https://projectpokemon.org/images/normal-sprite/koffing.gif",
    types: ["Poison"],
    attack: 65,
    defense: 95,
    hp: 40,
    moves: [
      { move: "Lanzallamas", move_dmg: 40 },
      { move: "Polvo Veneno", move_dmg: 0 },
      { move: "Tóxico", move_dmg: 0 },
      { move: "Explosión", move_dmg: 250 },
    ],
  },
  {
    id: 110,
    name: "Weezing",
    img: "https://projectpokemon.org/images/normal-sprite/weezing.gif",
    types: ["Poison"],
    attack: 90,
    defense: 120,
    hp: 65,
    moves: [
      { move: "Lanzallamas", move_dmg: 40 },
      { move: "Tóxico", move_dmg: 0 },
      { move: "Polvo Veneno", move_dmg: 0 },
      { move: "Explosión", move_dmg: 250 },
    ],
  },
  {
    id: 111,
    name: "Rhyhorn",
    img: "https://projectpokemon.org/images/normal-sprite/rhyhorn.gif",
    types: ["Ground", "Rock"],
    attack: 85,
    defense: 95,
    hp: 80,
    moves: [
      { move: "Tierra Viva", move_dmg: 35 },
      { move: "Roca Afilada", move_dmg: 50 },
      { move: "Golpe Cuerpo", move_dmg: 40 },
      { move: "Gruñido", move_dmg: 0 },
    ],
  },
  {
    id: 112,
    name: "Rhydon",
    img: "https://projectpokemon.org/images/normal-sprite/rhydon.gif",
    types: ["Ground", "Rock"],
    attack: 130,
    defense: 120,
    hp: 105,
    moves: [
      { move: "Golpe Cabeza", move_dmg: 50 },
      { move: "Terremoto", move_dmg: 80 },
      { move: "Megacuerno", move_dmg: 70 },
      { move: "Derribo", move_dmg: 45 },
    ],
  },
  {
    id: 113,
    name: "Chansey",
    img: "https://projectpokemon.org/images/normal-sprite/chansey.gif",
    types: ["Normal"],
    attack: 5,
    defense: 5,
    hp: 250,
    moves: [
      { move: "Doble Bofetón", move_dmg: 35 },
      { move: "Rayo", move_dmg: 60 },
      { move: "Canto", move_dmg: 0 },
      { move: "Pulso Cura", move_dmg: 0 },
    ],
  },
  {
    id: 114,
    name: "Tangela",
    img: "https://projectpokemon.org/images/normal-sprite/tangela.gif",
    types: ["Grass"],
    attack: 55,
    defense: 115,
    hp: 65,
    moves: [
      { move: "Látigo Cepa", move_dmg: 45 },
      { move: "Absorber", move_dmg: 20 },
      { move: "Paralizador", move_dmg: 0 },
      { move: "Bomba Germen", move_dmg: 55 },
    ],
  },
  {
    id: 115,
    name: "Kangaskhan",
    img: "https://projectpokemon.org/images/normal-sprite/kangaskhan.gif",
    types: ["Normal"],
    attack: 95,
    defense: 80,
    hp: 105,
    moves: [
      { move: "Golpe Furia", move_dmg: 45 },
      { move: "Cabezazo", move_dmg: 40 },
      { move: "Mega Puño", move_dmg: 80 },
      { move: "Terremoto", move_dmg: 80 },
    ],
  },
  {
    id: 116,
    name: "Horsea",
    img: "https://projectpokemon.org/images/normal-sprite/horsea.gif",
    types: ["Water"],
    attack: 40,
    defense: 70,
    hp: 30,
    moves: [
      { move: "Pistola Agua", move_dmg: 40 },
      { move: "Burbuja", move_dmg: 40 },
      { move: "Rayo Aurora", move_dmg: 65 },
      { move: "Hidropulso", move_dmg: 50 },
    ],
  },
  {
    id: 117,
    name: "Seadra",
    img: "https://projectpokemon.org/images/normal-sprite/seadra.gif",
    types: ["Water"],
    attack: 65,
    defense: 95,
    hp: 55,
    moves: [
      { move: "Burbuja", move_dmg: 40 },
      { move: "Hidropulso", move_dmg: 50 },
      { move: "Cabezazo", move_dmg: 40 },
      { move: "Rayo Aurora", move_dmg: 65 },
    ],
  },
  {
    id: 118,
    name: "Goldeen",
    img: "https://projectpokemon.org/images/normal-sprite/goldeen.gif",
    types: ["Water"],
    attack: 67,
    defense: 60,
    hp: 45,
    moves: [
      { move: "Pistola Agua", move_dmg: 40 },
      { move: "Cornada", move_dmg: 50 },
      { move: "Acua Jet", move_dmg: 40 },
      { move: "Golpe Cuerpo", move_dmg: 60 },
    ],
  },
  {
    id: 119,
    name: "Seaking",
    img: "https://projectpokemon.org/images/normal-sprite/seaking.gif",
    types: ["Water"],
    attack: 92,
    defense: 65,
    hp: 80,
    moves: [
      { move: "Cascada", move_dmg: 70 },
      { move: "Cornada", move_dmg: 50 },
      { move: "Rayo Aurora", move_dmg: 65 },
      { move: "Acua Cola", move_dmg: 60 },
    ],
  },
  {
    id: 120,
    name: "Staryu",
    img: "https://projectpokemon.org/images/normal-sprite/staryu.gif",
    types: ["Water"],
    attack: 45,
    defense: 55,
    hp: 30,
    moves: [
      { move: "Pistola Agua", move_dmg: 40 },
      { move: "Rayo Burbuja", move_dmg: 40 },
      { move: "Rayo Aurora", move_dmg: 65 },
      { move: "Hidropulso", move_dmg: 50 },
    ],
  },
  {
    id: 121,
    name: "Starmie",
    img: "https://projectpokemon.org/images/normal-sprite/starmie.gif",
    types: ["Water", "Psychic"],
    attack: 60,
    defense: 85,
    hp: 60,
    moves: [
      { move: "Hidrobomba", move_dmg: 90 },
      { move: "Rayo Aurora", move_dmg: 65 },
      { move: "Psíquico", move_dmg: 90 },
      { move: "Surf", move_dmg: 90 },
    ],
  },
  {
    id: 122,
    name: "Mr. Mime",
    img: "https://projectpokemon.org/images/normal-sprite/mr.mime.gif",
    types: ["Psychic", "Fairy"],
    attack: 45,
    defense: 65,
    hp: 40,
    moves: [
      { move: "Confusión", move_dmg: 50 },
      { move: "Psíquico", move_dmg: 90 },
      { move: "Doble Rayo", move_dmg: 70 },
      { move: "Pantalla de Luz", move_dmg: 0 },
    ],
  },
  {
    id: 123,
    name: "Scyther",
    img: "https://projectpokemon.org/images/normal-sprite/scyther.gif",
    types: ["Bug", "Flying"],
    attack: 110,
    defense: 80,
    hp: 70,
    moves: [
      { move: "Cuchillada", move_dmg: 60 },
      { move: "Tajo Aéreo", move_dmg: 60 },
      { move: "Danza Espada", move_dmg: 0 },
      { move: "Golpe Furia", move_dmg: 45 },
    ],
  },
  {
    id: 124,
    name: "Jynx",
    img: "https://projectpokemon.org/images/normal-sprite/jynx.gif",
    types: ["Ice", "Psychic"],
    attack: 50,
    defense: 35,
    hp: 65,
    moves: [
      { move: "Beso Amoroso", move_dmg: 0 },
      { move: "Rayo Hielo", move_dmg: 65 },
      { move: "Confusión", move_dmg: 50 },
      { move: "Ventisca", move_dmg: 80 },
    ],
  },
  {
    id: 125,
    name: "Electabuzz",
    img: "https://projectpokemon.org/images/normal-sprite/electabuzz.gif",
    types: ["Electric"],
    attack: 83,
    defense: 57,
    hp: 65,
    moves: [
      { move: "Puño Trueno", move_dmg: 75 },
      { move: "Impactrueno", move_dmg: 40 },
      { move: "Rayo", move_dmg: 60 },
      { move: "Pantalla de Luz", move_dmg: 0 },
    ],
  },
  {
    id: 126,
    name: "Magmar",
    img: "https://projectpokemon.org/images/normal-sprite/magmar.gif",
    types: ["Fire"],
    attack: 95,
    defense: 57,
    hp: 65,
    moves: [
      { move: "Ascuas", move_dmg: 40 },
      { move: "Llamarada", move_dmg: 90 },
      { move: "Puño Fuego", move_dmg: 75 },
      { move: "Pantalla de Humo", move_dmg: 0 },
    ],
  },
  {
    id: 127,
    name: "Pinsir",
    img: "https://projectpokemon.org/images/normal-sprite/pinsir.gif",
    types: ["Bug"],
    attack: 125,
    defense: 100,
    hp: 65,
    moves: [
      { move: "Golpe Mordaza", move_dmg: 50 },
      { move: "Tijera X", move_dmg: 80 },
      { move: "Cuchillada", move_dmg: 60 },
      { move: "Derribo", move_dmg: 45 },
    ],
  },
  {
    id: 128,
    name: "Tauros",
    img: "https://projectpokemon.org/images/normal-sprite/tauros.gif",
    types: ["Normal"],
    attack: 100,
    defense: 95,
    hp: 75,
    moves: [
      { move: "Embate", move_dmg: 50 },
      { move: "Pisotón", move_dmg: 45 },
      { move: "Golpe Cuerpo", move_dmg: 60 },
      { move: "Terremoto", move_dmg: 80 },
    ],
  },
  {
    id: 129,
    name: "Magikarp",
    img: "https://projectpokemon.org/images/normal-sprite/magikarp.gif",
    types: ["Water"],
    attack: 10,
    defense: 55,
    hp: 20,
    moves: [{ move: "Placaje", move_dmg: 20 }],
  },
  {
    id: 130,
    name: "Gyarados",
    img: "https://projectpokemon.org/images/normal-sprite/gyarados.gif",
    types: ["Water", "Flying"],
    attack: 125,
    defense: 79,
    hp: 95,
    moves: [
      { move: "Mordisco", move_dmg: 60 },
      { move: "Hidrobomba", move_dmg: 90 },
      { move: "Ciclón", move_dmg: 40 },
      { move: "Triturar", move_dmg: 80 },
    ],
  },
  {
    id: 131,
    name: "Lapras",
    img: "https://projectpokemon.org/images/normal-sprite/lapras.gif",
    types: ["Water", "Ice"],
    attack: 85,
    defense: 80,
    hp: 130,
    moves: [
      { move: "Canto Helado", move_dmg: 65 },
      { move: "Surf", move_dmg: 90 },
      { move: "Cabezazo", move_dmg: 40 },
      { move: "Ventisca", move_dmg: 80 },
    ],
  },
  {
    id: 132,
    name: "Ditto",
    img: "https://projectpokemon.org/images/normal-sprite/ditto.gif",
    types: ["Normal"],
    attack: 48,
    defense: 48,
    hp: 48,
    moves: [
      {
        move: "Placaje",
        dmg: 20,
      },
    ],
  },
  {
    id: 133,
    name: "Eevee",
    img: "https://projectpokemon.org/images/normal-sprite/eevee.gif",
    types: ["Normal"],
    attack: 55,
    defense: 50,
    hp: 55,
    moves: [
      { move: "Ataque Rápido", move_dmg: 40 },
      { move: "Mordisco", move_dmg: 60 },
      { move: "Refugio", move_dmg: 0 },
      { move: "Gruñido", move_dmg: 0 },
    ],
  },
  {
    id: 134,
    name: "Vaporeon",
    img: "https://projectpokemon.org/images/normal-sprite/vaporeon.gif",
    types: ["Water"],
    attack: 65,
    defense: 60,
    hp: 130,
    moves: [
      { move: "Pistola Agua", move_dmg: 40 },
      { move: "Hidrobomba", move_dmg: 90 },
      { move: "Rayo Aurora", move_dmg: 65 },
      { move: "Danza Lluvia", move_dmg: 0 },
    ],
  },
  {
    id: 135,
    name: "Jolteon",
    img: "https://projectpokemon.org/images/normal-sprite/jolteon.gif",
    types: ["Electric"],
    attack: 65,
    defense: 60,
    hp: 65,
    moves: [
      { move: "Impactrueno", move_dmg: 40 },
      { move: "Rayo", move_dmg: 60 },
      { move: "Chispa", move_dmg: 50 },
      { move: "Pantalla de Luz", move_dmg: 0 },
    ],
  },
  {
    id: 136,
    name: "Flareon",
    img: "https://projectpokemon.org/images/normal-sprite/flareon.gif",
    types: ["Fire"],
    attack: 130,
    defense: 60,
    hp: 65,
    moves: [
      { move: "Ascuas", move_dmg: 40 },
      { move: "Llamarada", move_dmg: 90 },
      { move: "Giro Fuego", move_dmg: 35 },
      { move: "Danza Llama", move_dmg: 50 },
    ],
  },
  {
    id: 137,
    name: "Porygon",
    img: "https://projectpokemon.org/images/normal-sprite/porygon.gif",
    types: ["Normal"],
    attack: 60,
    defense: 70,
    hp: 65,
    moves: [
      { move: "Conversion 2", move_dmg: 0 },
      { move: "Rayo", move_dmg: 60 },
      { move: "Psíquico", move_dmg: 90 },
      { move: "Triataque", move_dmg: 80 },
    ],
  },
  {
    id: 138,
    name: "Omanyte",
    img: "https://projectpokemon.org/images/normal-sprite/omanyte.gif",
    types: ["Rock", "Water"],
    attack: 40,
    defense: 100,
    hp: 35,
    moves: [
      { move: "Pistola Agua", move_dmg: 40 },
      { move: "Rayo Aurora", move_dmg: 65 },
      { move: "Bofetón Lodo", move_dmg: 20 },
      { move: "Hidropulso", move_dmg: 50 },
    ],
  },
  {
    id: 139,
    name: "Omastar",
    img: "https://projectpokemon.org/images/normal-sprite/omastar.gif",
    types: ["Rock", "Water"],
    attack: 60,
    defense: 125,
    hp: 70,
    moves: [
      { move: "Hidropulso", move_dmg: 50 },
      { move: "Cascada", move_dmg: 70 },
      { move: "Cabezazo", move_dmg: 40 },
      { move: "Rayo Aurora", move_dmg: 65 },
    ],
  },
  {
    id: 140,
    name: "Kabuto",
    img: "https://projectpokemon.org/images/normal-sprite/kabuto.gif",
    types: ["Rock", "Water"],
    attack: 80,
    defense: 90,
    hp: 30,
    moves: [
      { move: "Absorber", move_dmg: 20 },
      { move: "Rayo Burbuja", move_dmg: 40 },
      { move: "Golpe Cabeza", move_dmg: 40 },
      { move: "Hidropulso", move_dmg: 50 },
    ],
  },
  {
    id: 141,
    name: "Kabutops",
    img: "https://projectpokemon.org/images/normal-sprite/kabutops.gif",
    types: ["Rock", "Water"],
    attack: 115,
    defense: 105,
    hp: 60,
    moves: [
      { move: "Corte", move_dmg: 50 },
      { move: "Hidropulso", move_dmg: 50 },
      { move: "Cuchillada", move_dmg: 60 },
      { move: "Rayo Burbuja", move_dmg: 40 },
    ],
  },
  {
    id: 142,
    name: "Aerodactyl",
    img: "https://projectpokemon.org/images/normal-sprite/aerodactyl.gif",
    types: ["Rock", "Flying"],
    attack: 105,
    defense: 65,
    hp: 80,
    moves: [
      { move: "Mordisco", move_dmg: 60 },
      { move: "Golpe Aéreo", move_dmg: 60 },
      { move: "Roca Afilada", move_dmg: 50 },
      { move: "Hiperrayo", move_dmg: 90 },
    ],
  },
  {
    id: 143,
    name: "Snorlax",
    img: "https://projectpokemon.org/images/normal-sprite/snorlax.gif",
    types: ["Normal"],
    attack: 110,
    defense: 65,
    hp: 160,
    moves: [
      { move: "Golpe Cuerpo", move_dmg: 60 },
      { move: "Descanso", move_dmg: 0 },
      { move: "Pulso Dragón", move_dmg: 60 },
      { move: "Pisotón", move_dmg: 45 },
    ],
  },
  {
    id: 144,
    name: "Articuno",
    img: "https://projectpokemon.org/images/normal-sprite/articuno.gif",
    types: ["Ice", "Flying"],
    attack: 85,
    defense: 100,
    hp: 90,
    moves: [
      { move: "Rayo Hielo", move_dmg: 65 },
      { move: "Ventisca", move_dmg: 80 },
      { move: "Agilidad", move_dmg: 0 },
      { move: "Golpe Aéreo", move_dmg: 60 },
    ],
  },
  {
    id: 145,
    name: "Zapdos",
    img: "https://projectpokemon.org/images/normal-sprite/zapdos.gif",
    types: ["Electric", "Flying"],
    attack: 90,
    defense: 85,
    hp: 90,
    moves: [
      { move: "Rayo", move_dmg: 60 },
      { move: "Pico Taladro", move_dmg: 70 },
      { move: "Trueno", move_dmg: 90 },
      { move: "Pantalla de Luz", move_dmg: 0 },
    ],
  },
  {
    id: 146,
    name: "Moltres",
    img: "https://projectpokemon.org/images/normal-sprite/moltres.gif",
    types: ["Fire", "Flying"],
    attack: 100,
    defense: 90,
    hp: 90,
    moves: [
      { move: "Llamarada", move_dmg: 90 },
      { move: "Ascuas", move_dmg: 40 },
      { move: "Ataque Ala", move_dmg: 60 },
      { move: "Golpe Aéreo", move_dmg: 60 },
    ],
  },
  {
    id: 147,
    name: "Dratini",
    img: "https://projectpokemon.org/images/normal-sprite/dratini.gif",
    types: ["Dragon"],
    attack: 64,
    defense: 45,
    hp: 41,
    moves: [
      { move: "Ciclón", move_dmg: 40 },
      { move: "Cola Dragón", move_dmg: 60 },
      { move: "Rayo", move_dmg: 60 },
      { move: "Pulso Dragón", move_dmg: 65 },
    ],
  },
  {
    id: 148,
    name: "Dragonair",
    img: "https://projectpokemon.org/images/normal-sprite/dragonair.gif",
    types: ["Dragon"],
    attack: 84,
    defense: 65,
    hp: 61,
    moves: [
      { move: "Ciclón", move_dmg: 40 },
      { move: "Cola Dragón", move_dmg: 60 },
      { move: "Rayo", move_dmg: 60 },
      { move: "Pulso Dragón", move_dmg: 65 },
    ],
  },
  {
    id: 149,
    name: "Dragonite",
    img: "https://projectpokemon.org/images/normal-sprite/dragonite.gif",
    types: ["Dragon", "Flying"],
    attack: 134,
    defense: 95,
    hp: 91,
    moves: [
      { move: "Puño Trueno", move_dmg: 75 },
      { move: "Garra Dragón", move_dmg: 60 },
      { move: "Vuelo", move_dmg: 70 },
      { move: "Rayo Hielo", move_dmg: 70 },
    ],
  },
  {
    id: 150,
    name: "Mewtwo",
    img: "https://projectpokemon.org/images/normal-sprite/mewtwo.gif",
    types: ["Psychic"],
    attack: 110,
    defense: 90,
    hp: 106,
    moves: [
      { move: "Confusión", move_dmg: 50 },
      { move: "Psíquico", move_dmg: 90 },
      { move: "Rayo", move_dmg: 60 },
      { move: "Onda Mental", move_dmg: 70 },
    ],
  },
  {
    id: 151,
    name: "Mew",
    img: "https://projectpokemon.org/images/normal-sprite/mew.gif",
    types: ["Psychic"],
    attack: 100,
    defense: 100,
    hp: 100,
    moves: [
      { move: "Confusión", move_dmg: 50 },
      { move: "Mega Puño", move_dmg: 80 },
      { move: "Psíquico", move_dmg: 90 },
      { move: "Transformación", move_dmg: 0 },
    ],
  },
];
